#pragma once

#undef COMBO_COUNT
#define COMBO_COUNT 8

// Uncomment for ginny
//#define COMBO_COUNT 46

#define TAPPING_TERM    200
#undef COMBO_TERM
#define COMBO_TERM    50
#undef DEBOUNCE
#define DEBOUNCE    26

#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16
#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 0
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 60
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 7
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 0

