#!/bin/bash

cd "${QMK_HOME}"

mkdir -p "${QMK_HOME}"/keyboards/${KEYBOARD}/keymaps
ln -s /keyboard-layouts/keyboards/"${LOCAL_KEYBOARD_PATH}"/"${KEYMAP}" "${QMK_HOME}"/keyboards/${KEYBOARD}/keymaps/"${KEYMAP}"
ln -s /keyboard-layouts/users/"${KEYMAP}" "${QMK_HOME}"/users/"${KEYMAP}"

qmk compile -kb "${KEYBOARD}" -km "${KEYMAP}"

cp .build/*.hex /keyboard-layouts/
