#!/bin/bash

cd "${QMK_HOME}"

mkdir -p "${QMK_HOME}"/keyboards/${KEYBOARD}/keymaps
if [ -d "${QMK_HOME}"/keyboards/${KEYBOARD} ] ; then
  ln -s /keyboard-layouts/keyboards/"${LOCAL_KEYBOARD_PATH}"/"${KEYMAP}" "${QMK_HOME}"/keyboards/${KEYBOARD}/keymaps/"${KEYMAP}"
else
  ln -s /keyboard-layouts/keyboards/"${LOCAL_KEYBOARD_PATH}" "${QMK_HOME}"/keyboards/${KEYBOARD}
fi
ln -s /keyboard-layouts/users/"${KEYMAP}" "${QMK_HOME}"/users/"${KEYMAP}"

qmk compile -kb "${KEYBOARD}" -km "${KEYMAP}"

cp .build/*.hex /keyboard-layouts/
