#pragma once

#undef COMBO_COUNT
#define COMBO_COUNT 8

#define TAPPING_TERM    200
#undef COMBO_TERM
#define COMBO_TERM    50

#undef DEBOUNCE
#define DEBOUNCE    26

#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

#define TAPPING_FORCE_HOLD

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0

#undef MASTER_LEFT
#define MASTER_RIGHT

